version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html  # Cambia esto para apuntar a la raíz del proyecto
    networks:
      - laravel_network

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8081:80"  # Cambia 8080 a 8081 (o cualquier otro puerto disponible)
    volumes:
      - ./:/var/www/html  # Cambia esto para apuntar a la raíz del proyecto
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  db:
    image: mariadb:10.6
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel_network

volumes:
  dbdata:
    driver: local

networks:
  laravel_network:
    driver: bridge
